[[redirects]]
  from = "/"
  to = "/pages/welcome.html"
  force = true
  status = 200
  
[[redirects]]
  from = "/sim.html"
  to = "/pages/sim.html"
  force = true
  status = 200
  
[[redirects]]
  from "/info.html"
  to = "/pages/info.html"
  force = true
  status = 200
